name: Build
on: [push, pull_request]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install TeX Live
        uses: zauguin/install-texlive@v2
        with:
          packages: >
            pdflatex
      - run: pdflatex -interaction=nonstopmode Coverpage.ins
      - run: pdflatex -interaction=nonstopmode -shell-escape SimpleSample.tex
      - run: rm SimpleSample.aux
      - run: lualatex -interaction=nonstopmode -shell-escape SimpleSample.tex
      - run: ./release.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ctan
          path: CoverPage.tar.gz
