name: Build
on: [push, pull_request]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: CoverPage.ins
        uses: dante-ev/latex-action@edge
        with:
          root_file: CoverPage.ins
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: SimpleSample.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: SimpleSample.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      - name: release.sh
        uses: dante-ev/latex-action@edge
        with:
          entrypoint: ./release.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ctan
          path: CoverPage.tar.gz
